# Unit 5 Anthropology - Final Project

Exploring the AMNH collections database for mocassins and reporting their color combinations. 

Create at least two functions to find the following using Claire Heckel's moccasin data:
1. How many color combinations are used on moccasins? How many moccasins have a combination of 3 colors?
2. Which color combinations occur most often in our moccasins data (min/max)?
3. What are the three most common pairs of motifs on moccasins? What are the least common?

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
claire_data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ClairesMoccasinData - Data.csv")
claire_data.head()
color_combos_2 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/2_color_combos.txt")
color_combos_3 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/3_color_combos.txt")
color_combos_4 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/4_color_combos.txt")
color_combos_5 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/5_color_combos.txt")
motif_combos_3 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/3_motif_combos.txt")
motif_combos_4 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/4_motif_combos.txt")
motif_combos_5 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/5_motif_combos.txt")

In [ ]:
plains = claire_data.loc[claire_data["CULTURE"]==5] #filters
columns = ['ACCYEAR', 'CULTURE', 'LOCALE', 'SIZE', 'GENDER', 'BEADED',
       'QUILLED', 'PIGMENT1', 'TONGUETYPE', 'TONGUESEWN', 'CUFFTYPE',
       'CUFFSEWN', 'LACES', 'FRINGE', 'HEELTABS', 'DECOLAYOUT', 'BORDERMOTIF',
       'BORDERROWS', 'TOEMARKER']
plains = plains.drop(columns, axis=1)

In [ ]:
plains.columns
plainsMotifs = ['MOTIF_ANTELOPEHOOF', 'MOTIF_ARROW', 'MOTIF_BIRD', 'MOTIF_BOX',
       'MOTIF_BOXPLOT', 'MOTIF_CHECKER', 'MOTIF_CHEVRON', 'MOTIF_CROSSBAR',
       'MOTIF_DIAMO9', 'MOTIF_DRAGONFLY', 'MOTIF_ELKHOOF', 'MOTIF_HOURGLASS',
       'MOTIF_FEATHER', 'MOTIF_FILLEDUP', 'MOTIF_FULLPOINTS', 'MOTIF_HALFSTAR',
       'MOTIF_HEARTLUNGS', 'MOTIF_HORSETRACKS', 'MOTIF_IBAR', 'MOTIF_LEAF',
       'MOTIF_LIGHTNING', 'MOTIF_LONGCHECKER', 'MOTIF_MORNINGSTAR',
       'MOTIF_MOUNTAIN', 'MOTIF_POINTS', 'MOTIF_RABBITEARS',
       'MOTIF_RABBITTRACKS', 'MOTIF_SLANTBAR', 'MOTIF_SQUARECROSS',
       'MOTIF_STRIPES', 'MOTIF_TIPI', 'MOTIF_TRIANGLES', 'MOTIF_TURTLE',
       'MOTIF_TWISTED', 'MOTIF_VERTEBRAE', 'OTHER']
plainsColors = ['BLACK', 'TR_CRYSTAL', 'WHITE', 'PINK',
       'TR_RED', 'RED', 'TR_DKRED', 'ORANGE', 'YELLOW', 'TR_ORANGE',
       'TR_YELLOW', 'DKYELLOW', 'TR_TOPAZ', 'BROWN', 'TR_DKBROWN', 'TR_GREEN',
       'LTGREEN', 'TR_MEDGREEN', 'GREEN', 'TR_PEACOCKBL', 'TURQUOISE',
       'LTBLUE', 'POWDERBLUE', 'TR_TURQBLUE', 'STEELBLUE', 'MEDBLUE',
       'ROYALBLUE', 'TR_COBALT', 'NAVYBLUE', 'TR_DKMTBLUE', 'TR_DKPURPLE',
       'LAVENDER', 'SEAGREEN', 'FACETBRASS', 'REDWHITEINT']

In [ ]:
plains_colors = plains
plains_motifs = plains

In [ ]:
plains_colors = plains_colors.drop(plainsMotifs, axis = 1).reset_index()
plains_motifs = plains.drop(plainsColors, axis = 1).reset_index()

In [ ]:
plains_colors.head()

   index     CATNO  BLACK  ...  SEAGREEN  FACETBRASS  REDWHITEINT
0     79  502.4411      0  ...         0           0            0
1     80  502.4582      0  ...         0           0            0
2     81   502.393      1  ...         0           0            0
3     82  502.4608      0  ...         0           1            1
4     83  502.5343      0  ...         0           0            0

[5 rows x 37 columns]

In [ ]:
plains_motifs.head()

   index     CATNO  MOTIF_ANTELOPEHOOF  ...  MOTIF_TWISTED  MOTIF_VERTEBRAE  OTHER
0     79  502.4411                   0  ...              0                0      0
1     80  502.4582                   0  ...              0                0      0
2     81   502.393                   0  ...              0                0      0
3     82  502.4608                   0  ...              0                0      0
4     83  502.5343                   0  ...              0                0      0

[5 rows x 38 columns]

In [ ]:
#A funtion that finds all the colors = 1
#function input data frame, color combo
#for loop that goes through filtered data and identifies 1s
# for i in plains:
#   if i == plains["BLACK"]:
#     print("hdjcdj")
#   else:
#     print("jjdj")
# colors_list = ["BLACK",	"TR_CRYSTAL",	"WHITE",	"PINK",	"TR_RED",	"RED",	"TR_DKRED",	"ORANGE",	"YELLOW",	"TR_ORANGE", "TR_YELLOW",	"DKYELLOW",	"TR_TOPAZ",	"BROWN", "TR_DKBROWN",	"TR_GREEN", "LTGREEN",	"TR_MEDGREEN",	"GREEN",	"TR_PEACOCKBL",	"TURQUOISE",	"LTBLUE",	"POWDERBLUE",	"TR_TURQBLUE",	"STEELBLUE",	"MEDBLUE",	"ROYALBLUE",	"TR_COBALT",	"NAVYBLUE",	"TR_DKMTBLUE",	"TR_DKPURPLE",	"LAVENDER",	"SEAGREEN",	"FACETBRASS",	"REDWHITEINT"]
# #Go through each row, each row is a moccasin
# #Make a list for each row to store the colors on it?
# for i in plains_colors:
#   print(i)
#   if i in colors_list: #need to access values in each column not just the name 
#     if plains[colors_list[i]] == "1": 
#         print(plains[colors_list[i]])
# claire_data.head()

In [ ]:
moc_dict = {} #empty dict
colors_list = ["BLACK",	"TR_CRYSTAL",	"WHITE",	"PINK",	"TR_RED",	"RED",	"TR_DKRED",	"ORANGE",	"YELLOW",	"TR_ORANGE", "TR_YELLOW",	"DKYELLOW",	"TR_TOPAZ",	"BROWN", "TR_DKBROWN",	"TR_GREEN", "LTGREEN",	"TR_MEDGREEN",	"GREEN",	"TR_PEACOCKBL",	"TURQUOISE",	"LTBLUE",	"POWDERBLUE",	"TR_TURQBLUE",	"STEELBLUE",	"MEDBLUE",	"ROYALBLUE",	"TR_COBALT",	"NAVYBLUE",	"TR_DKMTBLUE",	"TR_DKPURPLE",	"LAVENDER",	"SEAGREEN",	"FACETBRASS",	"REDWHITEINT"]
for i in range(len(plains_colors)): #row
  for j in colors_list: #column
    if plains_colors[j][i] == 1:
      moc_dict[plains_colors["CATNO"][i]]

KeyError: ignored

In [ ]:
#how many color combinations are used on moccasins, how many are 3 color combos
# def color_checker(dataframe, color):
#   yellow_counter = 0
#   black_counter = 0
#   white_counter = 0
#   pink_counter = 0
#   red_counter = 0
#   orange_counter = 0
#   brown_counter = 0
#   green_counter = 0
#   turquoise_counter = 0
#   lavender_counter = 0
#   seagreen_counter = 0
#   for i in dataframe.columns:
#     if color in i:
#       if color == "YELLOW":
#         yellow_counter = yellow_counter + 1
#       elif color == "BLACK":
#         black_counter = black_counter + 1
#         # print(black_counter)
#       elif color == "WHITE":
#         white_counter = white_counter + 1
#         # print(white_counter)
#       elif color == "PINK":
#         pink_counter = pink_counter + 1
#         # print(pink_counter)
#       elif color == "RED":
#         red_counter = red_counter + 1
#         # print(red_counter)
#       elif color == "ORANGE":
#         orange_counter = orange_counter + 1
#         # print(orange_counter)
#       elif color == "BROWN":
#         brown_counter = brown_counter + 1
#         # print(brown_counter)
#       elif color == "GREEN":
#         green_counter = green_counter + 1
#         # print(green_counter)
#       elif color == "TURQUOISE":
#         turquoise_counter = turquoise_counter + 1
#         # print(turquoise_counter)
#       elif color == "LAVENDER":
#         lavender_counter = lavender_counter + 1
#         # print(lavender_counter)
#       elif color == "SEAGREEN":
#         seagreen_counter = seagreen_counter + 1
#         # print(seagreen_counter)

yellow: 3